name: Build and Release nopop.exe

on:
  push:
    tags:
      - 'v*'  # 仅在 push 以 "v" 开头的 tag（如 v1.0.0）时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    name: Build Executable
    runs-on: windows-latest  # 使用 Windows 进行打包

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 选择适合你的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole nopop.py

      - name: Rename and Move EXE
        run: |
          mkdir release
          mv dist/nopop.exe release/nopop.exe

      - name: Compute SHA256 on Windows
        id: hash
        shell: powershell
        run: |
          $hash = Get-FileHash -Algorithm SHA256 release\nopop.exe
          echo "HASH=$($hash.Hash)" >> $env:GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            SHA256: `${{ env.HASH }}`
          draft: false
          prerelease: false

      - name: Upload nopop.exe to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/nopop.exe
          asset_name: nopop.exe
          asset_content_type: application/octet-stream